language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: UZ/pAMhyY1MzMlOMo0su9PSzhC7ZypflLGMkLLBIfCrpkReoXsFeKxKCSDGK19s/fyjKPhsnM2ToMQi0iTtRDVM/KxFEerOUjdtTt5ANvyGD738UgwqJXEsNvLJEevMVsI1X3KYaqTJjJnRA/PfzrCHAtDfmMf7LGvmscRc5dUw3Uy3HbVnfD9zXf6u/WPBZ2b9dhD9xk6Xw8iHEPImSMxyqiM2+iY2miFKsdR5gaOXDXsJJ7bjExs6i+awbHGVUpg6wyg7q+Odeld4HIFDFnEWTfon+Gw2bhcfLfmMhaP9RqH3uhauZOzj29XRXM2fOtwiZZQnRjWsya8m0oKQbOkCRigqX7abDCWdWwJK8Iq3Al/dBe/1oem/GfY7PQXUZPkKTRBNnsiiSuULd5zGOuCXv08NC++Hu+DQn08/ca3gRBOGML7EUuG05SYFHWUn4xX27uoYKckIpan3Md6SEZ1sXj3jgp8gI0lf++ExKSu36+1RbJHt1lR9BHOkwX6zGpOPg7Tp3kKr2FqUdBIEKWuZvoy4Fp7Akx18A6IaHh6mRC8cEV8SzD1gcn8TX+EaxLX01zouUeB+2Kzwmg5s0S7fP5tqRlLUHegxR5knYejIoA3DQDKDyZE2nHISZo6AvqclM9uyBFipCYlMqgnF2Za+3cRCxQLJBqajaa2M2BCQ=
  app: dominikc-jalgoarena-auth
  on:
    repo: dominikc2/JAlgoArena-Auth
